# Title of your site (displayed in title tag at homepage)
title: HaloPekalongan - Portal Seni & Kebudayaan Kota Pekalongan

# Name of your site (displayed in the header)
name: HaloPekalongan

# Short bio or description (displayed in the header)
description: This page is just a statistical page that has no actual 'content', this is only for a preview of the results of the 1st Winner of the 2019 Scientific Week Competition for the Pekalongan Regional Level held by STMIK Widya Pratama Pekalongan.

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. https://sooluh.github.io or https://suluh.my.id)
# Used for Sitemap.xml and your RSS feed
url: https://pekalongan.now.sh

# If you're hosting your site at a Project repository on GitHub pages
# (https://sooluh.github.io/repository-name)
# and NOT your User repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Collections
collections:
  cultures:
    output: true
    permalink: /culture/:title
  tours:
    output: false

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: "highlight"

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
